#!/bin/bash

# Credit goes to Sol Does Tech for the script.
# https://github.com/SolDoesTech/hyprland
# I just edited as I see fit

# The following will be installed to run Hyprland on Asus G15 with RTX GPU
# This is a quick and dirty script there are no error checking
# Edit as required down below
#
# Below is a list of the packages that would be installed
#
# hyprland-nvidia-hidpi-git: This is the Hyprland compositor
# kitty: This is the default terminal
# waybar-hyprland: This is a fork of waybar with Hyprland workspace support
# swaybg: This is used to set a desktop background image
# swaylock-effects: This allows for the locking of the desktop its a fork that adds some editional visual effects
# wofi: This is an application launcher menu
# wlogout: This is a logout menu that allows for shutdown, reboot and sleep
# mako: This is a graphical notification daemon
# thunar with necessary plugins: This is a graphical file manager
# ttf-nerd-fonts-symbols-1000-em : some nerd fonts needed for proper icons in waybar
# ttf-nerd-fonts-symbols-common: Some nerd fonts for icons and overall look
# otf-font-awesome-5 # necessary for symbols / weather
# ttf-droid - suggested for international fonts to display properly
# polkit-gnome: needed to get superuser access on some graphical appliaction
# python-requests: needed for the weather module script to execute
# grim: This is a screenshot tool it grabs images from a Wayland compositor
# slurp: This helps with screenshots, it selects a region in a Wayland compositor
# viewnior: for photo viewing
# pamixer: This helps with audio settings such as volume
# brightnessctl: used to control monitor bright level
# bluez: the bluetooth service
# bluez-utils: command line utilities to interact with bluetooth devices
# blueman - Bluetooth manager
# lxappearance: used to set GTK theme
# dracula-gtk-theme: the Dracula theme, it fits the overall look and feel
# dracula-icons-git" set of icons to go with the Dracula theme
# bibata-cursor-theme-bin - cursor theme
# xdg-desktop-portal-hyprland-git: xdg-desktop-portal backend for hyprland
# mpv: for wofi-beats to work

#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then 
    echo -e "yay was located, moving on.\n"
    yay -Suy
else 
    echo -e "yay was not located, please install yay. Exiting script.\n"
    exit 
fi

### Disable wifi powersave mode ###
read -n1 -rep 'Would you like to disable wifi powersave? (y,n)' WIFI
if [[ $WIFI == "Y" || $WIFI == "y" ]]; then
    LOC="/etc/NetworkManager/conf.d/wifi-powersave.conf"
    echo -e "The following has been added to $LOC.\n"
    echo -e "[connection]\nwifi.powersave = 2" | sudo tee -a $LOC
    echo -e "\n"
    echo -e "Restarting NetworkManager service...\n"
    sudo systemctl restart NetworkManager
    sleep 3
fi

### Install all of the above pacakges ####
read -n1 -rep 'Would you like to install the packages? (y,n)' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
    yay -S --noconfirm hyprland-nvidia-git 
    yay -S --noconfirm waybar-hyprland-git 
    yay -S --noconfirm xdg-desktop-portal-hyprland-git 
    yay -S --noconfirm dracula-icons-git 
    
    yay -S --noconfirm foot swaybg swaylock-effects wofi wlogout mako thunar gvfs thunar-volman tumbler \
    ffmpegthumbs ttf-nerd-fonts-symbols-common ttf-nerd-fonts-symbols-1000-em otf-font-awesome-5 \
    polkit-gnome python-requests grim slurp pamixer brightnessctl viewnior dracula-gtk-theme \
    bluez bluez-utils blueman lxappearance bibata-cursor-theme-bin mpv \
      

    # Start the bluetooth service
    echo -e "Starting the Bluetooth Service...\n"
    sudo systemctl enable --now bluetooth.service
    sleep 2
    
    # Clean out other portals
    echo -e "Cleaning out conflicting xdg portals...\n"
    sudo pacman -R --noconfirm xdg-desktop-portal-gnome 
    sudo pacman -R --noconfirm xdg-desktop-portal-gtk 
    sudo pacman -R --noconfirm xdg-desktop-portal-kde 
    sudo pacman -R --noconfirm xdg-desktop-portal-wlr 
    sudo pacman -R --noconfirm xdg-desktop-portal-lxqt
fi

### Copy Config Files ###
read -n1 -rep 'Would you like to copy config and wallpaper files? (y,n)' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
    echo -e "Copying config files...\n"
    cp -R config/hypr ~/.config/
    cp -R config/foot ~/.config/
    cp -R config/swaylock ~/.config/
    cp -R config/wlogout ~/.config/
    cp -R wallpapers ~/Pictures/
    
    # Set some files as exacutable 
    chmod +x ~/.config/hypr/scripts/airplane-mode.sh
    chmod +x ~/.config/hypr/scripts/brightness
    chmod +x ~/.config/hypr/scripts/changeLayout
    chmod +x ~/.config/hypr/scripts/changeWallpaper
    chmod +x ~/.config/hypr/scripts/fullmenu
    chmod +x ~/.config/hypr/scripts/glassmorphismToggle
    chmod +x ~/.config/hypr/scripts/gtkthemes
    chmod +x ~/.config/hypr/scripts/lockscreen
    chmod +x ~/.config/hypr/scripts/menu
    chmod +x ~/.config/hypr/scripts/notifications
    chmod +x ~/.config/hypr/scripts/portal-arch-hyprland
    chmod +x ~/.config/hypr/scripts/screenshot
    chmod +x ~/.config/hypr/scripts/startup
    chmod +x ~/.config/hypr/scripts/statusbar
    chmod +x ~/.config/hypr/scripts/switch-lid.sh
    chmod +x ~/.config/hypr/scripts/touchpad.sh
    chmod +x ~/.config/hypr/scripts/volume
    chmod +x ~/.config/hypr/scripts/weather.sh
    chmod +x ~/.config/hypr/scripts/wofi-beats
fi
### Install software for Asus ROG laptops ###
read -n1 -rep 'Would you like to install Asus ROG software support? (y,n)' ROG
if [[ $ROG == "Y" || $ROG == "y" ]]; then
    echo -e "Installing ASUS ROG packages...\n"
    yay -S --noconfirm asusctl supergfxctl rog-control-center
    echo -e "Activating ROG services...\n"
    sudo systemctl daemon-reload && systemctl enable --now supergfxd
    sleep 2
fi

### Script is done ###
echo -e "Installation Completed.\n"
echo -e "You can start Hyprland by typing Hyprland (note the capital H) NOTE! it is highly recommended to reboot your computer first.\n"
read -n1 -rep 'Would you like to start Hyprland now? (y,n)' HYP
if [[ $HYP == "Y" || $HYP == "y" ]]; then
    exec Hyprland
else
    exit
fi
