#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Nordic'
ICONS='Shiny-Dark-Icons'
FONT='Cascadia Code Mono 14'
CURSOR='Bibata-Modern-Ice'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes