#!/bin/bash

## Files
CONFIG="$HOME/.config/hypr/wofi/config"
STYLE="$HOME/.config/hypr/wofi/style.css"
COLORS="$HOME/.config/hypr/wofi/colors"

## Wofi Command
wofi_command="wofi --show dmenu \
			--conf ${CONFIG} --style ${STYLE} --color ${COLORS} \
			--width=350 --height=380 \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--define=matching=fuzzy"


notification(){
  notify-send "Now Playing: Online Radio"
}

menu(){
  printf "1. Lofi Girl\n"
  printf "2. Box Lofi\n"
  printf "3. The Bootleg Boy\n"
  printf "4. Radio Spinner\n"
  printf "5. SmoothChill\n"
  printf "6. Relaxing Music\n"
  printf "7. K-Drama-OST\n"
  printf "8. Lofi Zone"
}

main() {
  choice=$(menu | ${wofi_command} | cut -d. -f1)

  case $choice in
    1)
      notification
      mpv "https://play.streamafrica.net/lofiradio"
      return
      ;;
    2)
      notification
      mpv "http://stream.zeno.fm/f3wvbbqmdg8uv"
      return
      ;;
    3)
      notification ;
      mpv "http://stream.zeno.fm/0r0xa792kwzuv"
      return
      ;;
    4)
      notification ;
      mpv "https://live.radiospinner.com/lofi-hip-hop-64"
      return
      ;;
    5)
      notification ;
      mpv "https://media-ssl.musicradio.com/SmoothChill"
      return
      ;;
    6)
      notification ;
      mpv --vid=no "https://youtube.com/playlist?list=PLMIbmfP_9vb8BCxRoraJpoo4q1yMFg4CE"
      return
      ;;
    7)
      notification ;
      mpv --shuffle --ytdl-raw-options="cookies=/tmp/cookies.txt" --vid=no https://www.youtube.com/watch?v=cRWUzbM2uLU&list=PLDtGd5Fw5_Gia0YBU7m0EOfqjNDBztHmo
      return
      ;;
    8)
      notification ;
      mpv --shuffle --ytdl-raw-options="cookies=/tmp/cookies.txt" --vid=no https://www.youtube.com/watch?v=GaW13eDQO6s
      return
      ;;
  esac
}

pkill -f http && notify-send "Online Radio stopped" || main
